In [1]:
import numpy as np
import copy
import math
dist = [[0,10,6,5,9],[10,0,8,7,2],[6,8,0,1,4],[5,7,1,0,3],[9,2,4,3,0]]
#clusters= [[0],[1],[2],[3],[4],[5],[6],[7],[8],[9],[10],[11]]
clusters = [[0],[1],[2],[3],[4]]
# mi = 50
# for i in range(len(dist)):
#     if min(dist[i]) < mi an:
#         mi = min(ele)
#lst = [[0],[0.23,0],[0.22,0.14,0],[0.37,0.19,0.13,0],[0.34,0.14,0.28,0.23,0],[0.24,0.24,0.1,0.22,0.39,0]]
lst = [[0],[10,0],[6,8,0],[5,7,1,0],[9,2,4,3,0]]
#data = [0.4,0.55,0.7,0.85,1,1.15,1.3,1.45,1.6, 2,2.2,2.4]
#x = [0.4,0.22,0.35,0.36,0.08,0.45]
#y = [0.53,0.38,0.32,0.19,0.41,0.3]
#clusters = [[],[]]
#M = 12
#lst = [[0],[10,0],[6,8,0],[5,7,1,0],[9,2,4,3,0]]
# lst = [[] for i in range(M)]
# dist = [[] for i in range(M)]
# for i in range(M):
#     for j in range(i+1):
#         lst[i].append(man(data[i],data[j]))
# for i in range(M):
#     for j in range(M):
#         if j <= i:
#             dist[i].append(lst[i][j])
#         else:
#             dist[i].append(lst[j][i])
#print(lst)
dst = []
n = 0
while len(clusters)>2:
    mi = 50
    for i in range(len(lst)):
        for j in range(i+1):
            if i != j:
                if lst[i][j] < mi:
                    mi = lst[i][j]
                    a,b = [i,j]
    print(a,b)
    clusters[b].extend(clusters[a])
    del clusters[a]
    #print(clusters)

    print(len(lst))
    for i in range(math.floor(len(lst[b])/2)):
        lst[b][i] = min(lst[a][i],lst[b][i])
    #del lst[a]
    #lst[a][b]
    for i in range(b+1,len(lst)):
        #print('yes',i,a)
        #print(dist[i+1][a],dist[i+1][b])
        lst[i][b] = min(lst[i][a],lst[i][b])
        if i > a:
            del lst[i][a]   #new statement
    del lst[a]
    # del dist[a]
    # for i in dist:
    #     print(dist)
    #     del i[a]
    # dist = copy.deepcopy(lst)
    # for i in range(len(dist)):
    #     for j in range(len(dist)):
    #         if i<j:
    #             dist[i].append(dist[j][i])
    for i in range(len(lst)):
        for j in range(len(lst)):
            if i<j:
                lst[i].append(lst[j][i])
    print('dist matrix', lst)
    #print('dist matrix 2', dist)
    print('clusters',clusters)
    n = n+1

for i in clusters:
    print(i)

3 2
5
dist matrix [[0, 10, 5, 9], [10, 0, 8, 2], [5, 8, 0, 3], [9, 2, 3, 0]]
clusters [[0], [1], [2, 3], [4]]
3 1
4
dist matrix [[0, 10, 5, 9, 9, 5], [9, 0, 8, 2, 3], [5, 3, 0, 3]]
clusters [[0], [1, 4], [2, 3]]
2 1
3
dist matrix [[0, 10, 5, 9, 9, 5, 5], [5, 0, 8, 2, 3]]
clusters [[0], [1, 4, 2, 3]]
[0]
[1, 4, 2, 3]


In [2]:
def man(a,b):
    return abs(a-b)

In [3]:
import numpy as np
import math
import sys
from sklearn import datasets
from sklearn.decomposition import PCA

In [4]:

def kernel(x,y):
    return math.exp((-(x-y)**2)/2)

In [5]:
def kernel2D(x,y):
    return math.exp((-((x[0]-y[0])**2 + (x[1]-y[1])**2)/2))

In [6]:
def computeMMD(x,y,N):
    g = [[kernel(x[0][i], x[0][j]) + kernel(y[0][i],y[0][j]) - (2*kernel(x[0][i], y[0][j])) for j in range(N)] for i in range(N)]
    return math.sqrt((sum(map(sum,g)) / N**2))

In [7]:
def computeMMD2(x,y,N):
    g = [[kernel2D(x[i], x[j]) + kernel2D(y[i],y[j]) - (2*kernel2D(x[i], y[j])) for j in range(N)] for i in range(N)]
    return math.sqrt((sum(map(sum,g)) / N**2))

In [8]:
def kernel4D(x,y):
    return math.exp(-((x[0]-y[0])**2 + (x[1]-y[1])**2 + (x[2]-y[2])**2 + (x[3]-y[3])**2))

In [9]:
def computeMMD4(x,y,N):
    g = [[kernel4D(x[i], x[j]) + kernel4D(y[i],y[j]) - (2*kernel4D(x[i], y[j])) for j in range(N)] for i in range(N)]
    return math.sqrt((sum(map(sum,g)) / N**2))

In [10]:
# def computeKS(a,b,N):

#     dsum = []
#     x = np.arange(-5,8,0.1)
#     for j in x:
#         suma = sum([i < j for i in a])
#         sumb = sum([i < j for i in b])
#         dsum.append(abs(suma - sumb)/N)
#     return max(dsum)

In [11]:
#lst = [[0,10,6,5,9],[10,0,8,7,2],[6,8,0,1,4],[5,7,1,0,3],[9,2,4,3,0]]
import random
M = 15      # total number of sequences
Mk = 5      # number of sequences per cluster
K = 3       # number of clusters
N = 1000     # number of elements in 1 sequence
#clusters = [[i] for i in range(M)]
#means = [0.4,0.55,0.7,0.85,1,1.15,1.3,1.46,1.6, 1.85,2,2.15]
#means = [i for i in range(K) for j in range(Mk)]
#means = [0.7,0.85,1,1.15,1.3, 1.7,1.85,2,2.15,2.3]
#correct = [[0,1,2,3,4,5,6,7,8],[9,10,11]]
correct = [[(Mk*i)+j for j in range(Mk)]for i in range(K)]
#correct = [[0,1,2,3,4],[5,6,7,8,9]]
#means = [[] for i in range(K)]
# delta = 0.1
# means = []
# s = (Mk+1)/2
# for i in range(K):
#     for j in range(Mk):
#         means.append(i + ((j+1-s)*delta/2) )
#means_2D = [[i,i] for i in range (2) for j in range(5)]
#means_2D = [[-0.1,-0.1],[-0.1,0.1],[0,0],[0.1,-0.1],[0.1,0.1],[0.9,-0.1],[0.9,0.1],[1,0],[1.1,-0.1],[1.1,0.1]]
#cov = [[1,0.1],[0.1,1]]
print(N)
#print(means)
print(correct)
sub = [(50*j + i) for j in range(3) for i in range(5)]
sub = [0, 1, 2, 3, 4, 50, 51, 52, 54, 55, 100, 101, 102, 103, 104]
print(sub)

1000
[[0, 1, 2, 3, 4], [5, 6, 7, 8, 9], [10, 11, 12, 13, 14]]
[0, 1, 2, 3, 4, 50, 51, 52, 54, 55, 100, 101, 102, 103, 104]


In [12]:
# import some data to play with
iris = datasets.load_iris()
X = iris.data
cov = 0.1 * np.eye(4)


In [13]:
for i in sub:
    print(X[i,:])

[5.1 3.5 1.4 0.2]
[4.9 3.  1.4 0.2]
[4.7 3.2 1.3 0.2]
[4.6 3.1 1.5 0.2]
[5.  3.6 1.4 0.2]
[7.  3.2 4.7 1.4]
[6.4 3.2 4.5 1.5]
[6.9 3.1 4.9 1.5]
[6.5 2.8 4.6 1.5]
[5.7 2.8 4.5 1.3]
[6.3 3.3 6.  2.5]
[5.8 2.7 5.1 1.9]
[7.1 3.  5.9 2.1]
[6.3 2.9 5.6 1.8]
[6.5 3.  5.8 2.2]


In [ ]:
import math
total = 0
error = 0
while total < 20:

    clusters = [[i] for i in range(M)]
    total += 1
    lst = [[] for i in range(M)]
    #a = [np.random.normal(means[i],1,(1,N)) for i in range(M)]
    y = np.asarray([np.random.multivariate_normal(X[i],cov,N) for i in sub])
    #y = np.asarray(a)
    lst = [[computeMMD4(y[i,:,:],y[j,:,:],N) for j in range(i+1)] for i in range(M)]
    #lst = [[computeMMD(y[i,:],y[j,:],N) for j in range(i+1)] for i in range(M)]
    #lst = [[computeMMD2(y[i,:][0],y[j,:][0],N) for j in range(i+1)] for i in range(M)]

    for i in range(M):
        for j in range(M):
            if i<j:
                lst[i].append(lst[j][i])
    print(lst)
    n = 0
    while len(clusters)>K:

        ####    FIND MINIMUM    ####

        #mi = sys.float_info.max
        mi = 100
        for i in range(len(lst)):
            for j in range(i+1):
                if i != j:
                    if lst[i][j] < mi:
                        mi = lst[i][j]
                        a,b = [i,j]
        #print(a,b)
        clusters[b].extend(clusters[a])
        del clusters[a]
        #print(clusters)

        ####    MERGE ROWS  ####

        for i in range(len(lst[b])):        #merge rows 'a' and 'b'
            if min(lst[a][i],lst[b][i]) != 0:
                lst[b][i] = min(lst[a][i],lst[b][i])
        del lst[a]

        ####    UPDATE ROWS     ####

        for i in range(len(lst)):       #update all other rows
            if i!=b:
                lst[i][b] = min(lst[i][a],lst[i][b])
            del lst[i][a]   #new statement

        #print('dist matrix', lst)
        #print('dist matrix 2', dist)
        #print('clusters',clusters)
        n = n+1

    clusters.sort()
    C_sort = []
    for x in clusters:
        x.sort()
        C_sort.append(x)

    print(C_sort)
    #print(centers)

    if correct != C_sort:
        error = error + 1
        print('L')
    else:
        print('W')

Pe = error/total
print(error)
lnPe = math.log(Pe)
print(total,lnPe)